# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | . | https://www.etsy.com
    self.driver.get("https://www.etsy.com")
    # 2 | pause | . | 3000
    time.sleep(3)
    # 4 | type | css=input[placeholder*='Search'] | Fall Style Gifts
    self.driver.find_element(By.CSS_SELECTOR, "input[placeholder*=\'Search\']").send_keys("Fall Style Gifts")
    # 5 | click | css=button[type='submit'] | 
    self.driver.find_element(By.CSS_SELECTOR, "button[type=\'submit\']").click()
    # 6 | waitForElementPresent | css=.listing-link | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".listing-link")))
    # 7 | executeScript | var products = []; document.querySelectorAll('.listing-link').forEach(function(el) {     var aTag = el.querySelector('a');     if (!aTag) return;  var imgTag = aTag.querySelector('img');     products.push({         title: aTag.getAttribute('aria-label') || '',         href: aTag.href || '',         img: imgTag ? imgTag.src : ''     }); }); return JSON.stringify(products); | all
    self.vars["all"] = self.driver.execute_script("var products = []; document.querySelectorAll(\'.listing-link\').forEach(function(el) {     var aTag = el.querySelector(\'a\');     if (!aTag) return;  var imgTag = aTag.querySelector(\'img\');     products.push({         title: aTag.getAttribute(\'aria-label\') || \'\',         href: aTag.href || \'\',         img: imgTag ? imgTag.src : \'\'     }); }); return JSON.stringify(products);")
    # 8 | echo | ${all} | 
    print("{}".format(self.vars["all"]))
    # 9 | executeScript | return document.querySelectorAll('.listing-link a').length;  | productCount
    self.vars["productCount"] = self.driver.execute_script("return document.querySelectorAll(\'.listing-link a\').length;")
    # 10 | store | 0 | i
    self.vars["i"] = "0"
    # 11 | while | ${i} < ${productCount} | 
    while self.driver.execute_script("return (arguments[0] < arguments[1])", self.vars["i"],self.vars["productCount"]):
      # 14 | executeScript | var el = document.querySelector('p.wt-text-title-small.wt-sem-text-critical.appears-ready');  return el ? el.textContent : 'No urgency info';  | urgencyText
      self.vars["urgencyText"] = self.driver.execute_script("var el = document.querySelector(\'p.wt-text-title-small.wt-sem-text-critical.appears-ready\');  return el ? el.textContent : \'No urgency info\';")
      # 15 | echo | ${urgencyText} | 
      print("{}".format(self.vars["urgencyText"]))
      # 17 | waitForElementPresent | css=.listing-link a  | 5000
      WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".listing-link a ")))
      # 19 | end |  | 
  
